name: test code 
on:
    pull request:
      paths:
        - us_visa/**
        - test/**
        - config/**

jobs:
  test_model:
    name: Test data ingestion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Environment setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run Tests
          run: pytest     
